[package]
name = "wordcut_engine_nif"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "wordcut_engine_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.26.0"
wordcut-engine = "1.1.5"
